### ISSUE TITLE
Add a number of docs from Canton into this repo to unblock current HA and Scaling work

### ISSUE THREAD

**Issue by da-katmurp** [digital-asset/docs.daml.com#143]
I am currently blocked on HA and Scaling documentation due to problems that arose when I was trying to delete a doc from the Canton snapshot to remove errors in the build. 

For reference: https://github.com/digital-asset/docs.daml.com/pull/138

@garyverhaegen-da suggested that to solve this we could remove the whole section from Canton and add it directly here.

The docs that need to come into the `main` branch are the `rst` files for:

https://docs.daml.com/canton/architecture/ha.html
https://docs.daml.com/canton/architecture/ha/overview.html
https://docs.daml.com/canton/architecture/ha/participant.html
https://docs.daml.com/canton/architecture/ha/domain.html

They also need to be removed from the Canton repo.

**Comment by da-katmurp** [comment]
any idea on timeline on this one @garyverhaegen-da? I can't do this.

**Comment by garyverhaegen-da** [comment]
I should be able to get to this early next week.

**Comment by garyverhaegen-da** [comment]
@da-katmurp I believe this is resolved. If not, could you please point out what is missing?

**Comment by da-katmurp** [comment]
Yes all good now.
