### ISSUE TITLE
Search broken for Javadocs of Java bindings

### ISSUE THREAD

**Issue by wallacekelly-da** [digital-asset/docs.daml.com#336]
**Steps to Reproduce**

1. Browse to <https://docs.daml.com/app-dev/bindings-java/javadocs/com/daml/ledger/javaapi/data/codegen/Contract.html>.
2. In the search box in the upper-right corner, type "ActiveContracts" and press ENTER.

**Expected Behavior**

The page <https://docs.daml.com/app-dev/bindings-java/javadocs/com/daml/ledger/javaapi/data/ActiveContracts.html> opens.

**Actual Results**

The page <https://docs.daml.com/app-dev/bindings-java/javadocs/undefined/com/daml/ledger/javaapi/data/ActiveContracts.html> opens.

(Notice the `undefined` in the URL.)

<img width="872" alt="image" src="https://github.com/digital-asset/docs.daml.com/assets/116685059/4ef3467b-99e6-43d8-97d6-ce2e4f4bd7cb">

**Comment by garyverhaegen-da** [comment]
Confirmed working on the live site.
