### ISSUE TITLE
Current docs are missing style sheets?

### ISSUE THREAD

**Issue by davebryson** [digital-asset/docs.daml.com#752]
It seems like the latest deployed docs (at https://docs.daml.com/) are missing the style sheets.  I've checked this on 2 separate browsers with the same results.  Here's a screen shot of what I'm seeing.  This wasn't like this last week

<img width="827" alt="Screenshot 2024-07-15 at 9 55 44 AM" src="https://github.com/user-attachments/assets/5e6cc317-0b4e-4b79-85ec-9c7346d53c37">

**Comment by yves-da** [comment]
Fixed with https://github.com/digital-asset/docs.daml.com/pull/754
