### ISSUE TITLE
Properly reference `logout` commands in `apis.rst`

### ISSUE THREAD

**Issue by cgrigis-da** [digital-asset/docs.daml.com#784]
When docs are re-enabled for `3.x`: https://github.com/DACH-NY/canton/issues/16155

Replace with references to the commands, e.g. 
```
:ref:`participant <domains.logout>`
```
and 
```
:ref:`mediator <sequencer_connection.logout>`
```

**Comment by yves-da** [comment]
CC @cgrigis-da 

Replaced by https://github.com/DACH-NY/canton/issues/22919

**Comment by cgrigis-da** [comment]
Thank you @yves-da!
