### ISSUE TITLE
Update docs 3.1 to point to latest canton snapshot

### ISSUE THREAD

**Issue by JoaoSa-da** [digital-asset/docs.daml.com#832]

**Comment by yves-da** [comment]
Close because it's obsolete. The Canton 3.* docs are now in the Canton repo again. So, the source (code) includes can be referenced directly. No need for using or having a canton (snapshot) artefact anymore.

**Comment by yves-da** [comment]
See also
* https://github.com/DACH-NY/canton/issues/22917
